<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PTG.ContractReportingRepair</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Reference Include="PTGOilSystem.Web"><HintPath>/runtime/PTGOilSystem.Web.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Microsoft.EntityFrameworkCore"><HintPath>/runtime/Microsoft.EntityFrameworkCore.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Abstractions"><HintPath>/runtime/Microsoft.EntityFrameworkCore.Abstractions.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="Microsoft.EntityFrameworkCore.Relational"><HintPath>/runtime/Microsoft.EntityFrameworkCore.Relational.dll</HintPath><Private>false</Private></Reference>
</ItemGroup>
</Project>
