<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>PTG.ContractReportingRepair.Tests</AssemblyName></PropertyGroup>
<ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" />
<Reference Include="PTG.ContractReportingRepair"><HintPath>../ContractReportingRepair/bin/Release/net8.0/PTG.ContractReportingRepair.dll</HintPath></Reference>
<Reference Include="Microsoft.EntityFrameworkCore.Relational"><HintPath>/runtime/Microsoft.EntityFrameworkCore.Relational.dll</HintPath><Private>false</Private></Reference>
<Reference Include="PTGOilSystem.Web"><HintPath>/runtime/PTGOilSystem.Web.dll</HintPath><Private>false</Private></Reference>
<Reference Include="Microsoft.EntityFrameworkCore"><HintPath>/runtime/Microsoft.EntityFrameworkCore.dll</HintPath><Private>false</Private></Reference>
<Reference Include="Microsoft.EntityFrameworkCore.Abstractions"><HintPath>/runtime/Microsoft.EntityFrameworkCore.Abstractions.dll</HintPath><Private>false</Private></Reference>
</ItemGroup></Project>