using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PTGOilSystem.Web.Migrations
{
    /// <inheritdoc />
    public partial class AddCurrencyPartnerUnitAndMultiCurrencySupport : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "SalesTransactions" ADD COLUMN IF NOT EXISTS "AppliedFxRateToUsd" numeric(18,6);
                ALTER TABLE "SalesTransactions" ADD COLUMN IF NOT EXISTS "Currency" character varying(10) NOT NULL DEFAULT 'USD';
                ALTER TABLE "SalesTransactions" ADD COLUMN IF NOT EXISTS "TotalInCurrency" numeric(18,4) NOT NULL DEFAULT 0;
                ALTER TABLE "SalesTransactions" ADD COLUMN IF NOT EXISTS "UnitPriceInCurrency" numeric(18,4) NOT NULL DEFAULT 0;

                ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "UnitId" integer;

                ALTER TABLE "ExpenseTransactions" ADD COLUMN IF NOT EXISTS "Amount" numeric(18,4) NOT NULL DEFAULT 0;
                ALTER TABLE "ExpenseTransactions" ADD COLUMN IF NOT EXISTS "AppliedFxRateToUsd" numeric(18,6);
                ALTER TABLE "ExpenseTransactions" ADD COLUMN IF NOT EXISTS "Currency" character varying(10) NOT NULL DEFAULT 'USD';

                ALTER TABLE "Contracts" ADD COLUMN IF NOT EXISTS "AppliedFxRateToUsd" numeric(18,6);
                ALTER TABLE "Contracts" ADD COLUMN IF NOT EXISTS "OwnershipType" integer NOT NULL DEFAULT 1;
                ALTER TABLE "Contracts" ADD COLUMN IF NOT EXISTS "UnitPriceInCurrency" numeric(18,4);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Currencies" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Code" character varying(10) NOT NULL,
                    "Name" character varying(100) NOT NULL,
                    "NamePersian" character varying(100),
                    "Symbol" character varying(20),
                    "IsActive" boolean NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone,
                    "CreatedByUserId" integer,
                    "UpdatedByUserId" integer,
                    CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Partners" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Code" character varying(50) NOT NULL,
                    "Name" character varying(200) NOT NULL,
                    "NamePersian" character varying(200),
                    "Country" character varying(20),
                    "ContactPerson" character varying(100),
                    "Phone" character varying(50),
                    "IsActive" boolean NOT NULL,
                    "Notes" character varying(1000),
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone,
                    "CreatedByUserId" integer,
                    "UpdatedByUserId" integer,
                    CONSTRAINT "PK_Partners" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Units" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Code" character varying(20) NOT NULL,
                    "Name" character varying(100) NOT NULL,
                    "NamePersian" character varying(100),
                    "Symbol" character varying(20),
                    "IsActive" boolean NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone,
                    "CreatedByUserId" integer,
                    "UpdatedByUserId" integer,
                    CONSTRAINT "PK_Units" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public'
                          AND table_name = 'ContractPartners')
                    AND EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'ContractPartners'
                          AND column_name = 'CompanyId')
                    AND NOT EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public'
                          AND table_name = 'ContractPartners_LegacyBackup')
                    THEN
                        ALTER TABLE "ContractPartners" RENAME TO "ContractPartners_LegacyBackup";

                        IF EXISTS (
                            SELECT 1 FROM pg_constraint WHERE conname = 'PK_ContractPartners') THEN
                            ALTER TABLE "ContractPartners_LegacyBackup"
                                RENAME CONSTRAINT "PK_ContractPartners" TO "PK_ContractPartners_LegacyBackup";
                        END IF;

                        IF EXISTS (
                            SELECT 1 FROM pg_constraint WHERE conname = 'FK_ContractPartners_Contracts_ContractId') THEN
                            ALTER TABLE "ContractPartners_LegacyBackup"
                                RENAME CONSTRAINT "FK_ContractPartners_Contracts_ContractId" TO "FK_ContractPartners_LegacyBackup_Contracts_ContractId";
                        END IF;

                        IF EXISTS (
                            SELECT 1 FROM pg_constraint WHERE conname = 'FK_ContractPartners_Companies_CompanyId') THEN
                            ALTER TABLE "ContractPartners_LegacyBackup"
                                RENAME CONSTRAINT "FK_ContractPartners_Companies_CompanyId" TO "FK_ContractPartners_LegacyBackup_Companies_CompanyId";
                        END IF;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "ContractPartners" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ContractId" integer NOT NULL,
                    "PartnerId" integer NOT NULL,
                    "SharePercent" numeric(9,4) NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone,
                    "CreatedByUserId" integer,
                    "UpdatedByUserId" integer,
                    CONSTRAINT "PK_ContractPartners" PRIMARY KEY ("Id")
                );

                ALTER TABLE "ContractPartners" ADD COLUMN IF NOT EXISTS "ContractId" integer;
                ALTER TABLE "ContractPartners" ADD COLUMN IF NOT EXISTS "PartnerId" integer;
                ALTER TABLE "ContractPartners" ADD COLUMN IF NOT EXISTS "SharePercent" numeric(9,4);
                ALTER TABLE "ContractPartners" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamp with time zone;
                ALTER TABLE "ContractPartners" ADD COLUMN IF NOT EXISTS "UpdatedAtUtc" timestamp with time zone;
                ALTER TABLE "ContractPartners" ADD COLUMN IF NOT EXISTS "CreatedByUserId" integer;
                ALTER TABLE "ContractPartners" ADD COLUMN IF NOT EXISTS "UpdatedByUserId" integer;

                UPDATE "ContractPartners"
                SET "CreatedAtUtc" = COALESCE("CreatedAtUtc", NOW())
                WHERE "CreatedAtUtc" IS NULL;

                UPDATE "ContractPartners"
                SET "SharePercent" = COALESCE("SharePercent", 0)
                WHERE "SharePercent" IS NULL;

                ALTER TABLE "ContractPartners" ALTER COLUMN "ContractId" SET NOT NULL;
                ALTER TABLE "ContractPartners" ALTER COLUMN "PartnerId" SET NOT NULL;
                ALTER TABLE "ContractPartners" ALTER COLUMN "SharePercent" SET NOT NULL;
                ALTER TABLE "ContractPartners" ALTER COLUMN "CreatedAtUtc" SET NOT NULL;
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Products_UnitId" ON "Products" ("UnitId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_ContractPartners_ContractId_PartnerId" ON "ContractPartners" ("ContractId", "PartnerId");
                CREATE INDEX IF NOT EXISTS "IX_ContractPartners_PartnerId" ON "ContractPartners" ("PartnerId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Currencies_Code" ON "Currencies" ("Code");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Partners_Code" ON "Partners" ("Code");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Units_Code" ON "Units" ("Code");
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Products_Units_UnitId') THEN
                        ALTER TABLE "Products"
                            ADD CONSTRAINT "FK_Products_Units_UnitId"
                            FOREIGN KEY ("UnitId") REFERENCES "Units" ("Id") ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ContractPartners_Contracts_ContractId') THEN
                        ALTER TABLE "ContractPartners"
                            ADD CONSTRAINT "FK_ContractPartners_Contracts_ContractId"
                            FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("Id") ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ContractPartners_Partners_PartnerId') THEN
                        ALTER TABLE "ContractPartners"
                            ADD CONSTRAINT "FK_ContractPartners_Partners_PartnerId"
                            FOREIGN KEY ("PartnerId") REFERENCES "Partners" ("Id") ON DELETE RESTRICT;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                INSERT INTO "Currencies" ("Code", "Name", "NamePersian", "Symbol", "IsActive", "CreatedAtUtc", "UpdatedAtUtc", "CreatedByUserId", "UpdatedByUserId")
                VALUES
                    ('USD', 'US Dollar', 'دالر امریکایی', '$', TRUE, TIMESTAMPTZ '2026-04-28 00:00:00+00', NULL, NULL, NULL),
                    ('AFN', 'Afghan Afghani', 'افغانی', '؋', TRUE, TIMESTAMPTZ '2026-04-28 00:00:00+00', NULL, NULL, NULL),
                    ('EUR', 'Euro', 'یورو', '€', TRUE, TIMESTAMPTZ '2026-04-28 00:00:00+00', NULL, NULL, NULL)
                ON CONFLICT ("Code") DO NOTHING;

                INSERT INTO "Units" ("Code", "Name", "NamePersian", "Symbol", "IsActive", "CreatedAtUtc", "UpdatedAtUtc", "CreatedByUserId", "UpdatedByUserId")
                VALUES
                    ('MT', 'Metric Ton', 'تن متریک', 'MT', TRUE, TIMESTAMPTZ '2026-04-28 00:00:00+00', NULL, NULL, NULL),
                    ('LTR', 'Liter', 'لیتر', 'LTR', TRUE, TIMESTAMPTZ '2026-04-28 00:00:00+00', NULL, NULL, NULL)
                ON CONFLICT ("Code") DO NOTHING;
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public'
                          AND table_name = 'ContractPartners_LegacyBackup')
                    THEN
                        INSERT INTO "Partners" ("Code", "Name", "NamePersian", "Country", "ContactPerson", "Phone", "IsActive", "Notes", "CreatedAtUtc", "UpdatedAtUtc", "CreatedByUserId", "UpdatedByUserId")
                        SELECT DISTINCT
                            LEFT(COALESCE(NULLIF(TRIM(c."Code"), ''), 'COMP-' || c."Id"::text), 50),
                            LEFT(COALESCE(NULLIF(TRIM(c."Name"), ''), 'Legacy Company ' || c."Id"::text), 200),
                            LEFT(NULLIF(TRIM(c."NamePersian"), ''), 200),
                            LEFT(NULLIF(TRIM(c."Country"), ''), 20),
                            NULL,
                            NULL,
                            COALESCE(c."IsActive", TRUE),
                            'Migrated from legacy contract partner links.',
                            COALESCE(MIN(cp."CreatedAtUtc"), NOW()),
                            MAX(cp."UpdatedAtUtc"),
                            MIN(cp."CreatedByUserId"),
                            MAX(cp."UpdatedByUserId")
                        FROM "ContractPartners_LegacyBackup" cp
                        JOIN "Companies" c ON c."Id" = cp."CompanyId"
                        GROUP BY c."Id", c."Code", c."Name", c."NamePersian", c."Country", c."IsActive"
                        ON CONFLICT ("Code") DO NOTHING;

                        INSERT INTO "ContractPartners" ("ContractId", "PartnerId", "SharePercent", "CreatedAtUtc", "UpdatedAtUtc", "CreatedByUserId", "UpdatedByUserId")
                        SELECT migrated."ContractId",
                               migrated."PartnerId",
                               migrated."SharePercent",
                               migrated."CreatedAtUtc",
                               migrated."UpdatedAtUtc",
                               migrated."CreatedByUserId",
                               migrated."UpdatedByUserId"
                        FROM (
                            SELECT DISTINCT ON (cp."ContractId", p."Id")
                                cp."ContractId",
                                p."Id" AS "PartnerId",
                                cp."SharePercentage"::numeric(9,4) AS "SharePercent",
                                COALESCE(cp."CreatedAtUtc", NOW()) AS "CreatedAtUtc",
                                cp."UpdatedAtUtc",
                                cp."CreatedByUserId",
                                cp."UpdatedByUserId"
                            FROM "ContractPartners_LegacyBackup" cp
                            JOIN "Companies" c ON c."Id" = cp."CompanyId"
                            JOIN "Partners" p ON p."Code" = LEFT(COALESCE(NULLIF(TRIM(c."Code"), ''), 'COMP-' || c."Id"::text), 50)
                            WHERE COALESCE(cp."IsActive", TRUE)
                            ORDER BY cp."ContractId", p."Id", COALESCE(cp."UpdatedAtUtc", cp."CreatedAtUtc") DESC, cp."Id" DESC
                        ) AS migrated
                        ON CONFLICT ("ContractId", "PartnerId") DO UPDATE
                        SET "SharePercent" = EXCLUDED."SharePercent",
                            "UpdatedAtUtc" = COALESCE(EXCLUDED."UpdatedAtUtc", "ContractPartners"."UpdatedAtUtc"),
                            "UpdatedByUserId" = COALESCE(EXCLUDED."UpdatedByUserId", "ContractPartners"."UpdatedByUserId");
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                UPDATE "Products"
                SET "UnitId" = (
                    SELECT "Id"
                    FROM "Units"
                    WHERE "Code" = CASE
                        WHEN COALESCE(NULLIF(TRIM("Products"."UnitOfMeasure"), ''), 'MT') = 'LTR' THEN 'LTR'
                        ELSE 'MT'
                    END
                )
                WHERE "UnitId" IS NULL;

                UPDATE "Products"
                SET "UnitOfMeasure" = COALESCE(NULLIF(TRIM("UnitOfMeasure"), ''), 'MT');

                UPDATE "Contracts"
                SET "OwnershipType" = 1,
                    "UnitPriceInCurrency" = COALESCE("UnitPriceInCurrency", "UnitPriceUsd"),
                    "AppliedFxRateToUsd" = CASE
                        WHEN COALESCE(NULLIF(TRIM("Currency"), ''), 'USD') = 'USD' AND "UnitPriceUsd" IS NOT NULL THEN 1
                        ELSE "AppliedFxRateToUsd"
                    END,
                    "Currency" = COALESCE(NULLIF(TRIM("Currency"), ''), 'USD');

                UPDATE "SalesTransactions"
                SET "Currency" = 'USD',
                    "UnitPriceInCurrency" = "UnitPriceUsd",
                    "TotalInCurrency" = "TotalUsd",
                    "AppliedFxRateToUsd" = 1
                WHERE "Currency" IS DISTINCT FROM 'USD'
                   OR "UnitPriceInCurrency" IS DISTINCT FROM "UnitPriceUsd"
                   OR "TotalInCurrency" IS DISTINCT FROM "TotalUsd"
                   OR "AppliedFxRateToUsd" IS DISTINCT FROM 1;

                UPDATE "ExpenseTransactions"
                SET "Currency" = 'USD',
                    "Amount" = "AmountUsd",
                    "AppliedFxRateToUsd" = 1
                WHERE "Currency" IS DISTINCT FROM 'USD'
                   OR "Amount" IS DISTINCT FROM "AmountUsd"
                   OR "AppliedFxRateToUsd" IS DISTINCT FROM 1;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Products_Units_UnitId') THEN
                        ALTER TABLE "Products" DROP CONSTRAINT "FK_Products_Units_UnitId";
                    END IF;

                    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ContractPartners_Contracts_ContractId') THEN
                        ALTER TABLE "ContractPartners" DROP CONSTRAINT "FK_ContractPartners_Contracts_ContractId";
                    END IF;

                    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ContractPartners_Partners_PartnerId') THEN
                        ALTER TABLE "ContractPartners" DROP CONSTRAINT "FK_ContractPartners_Partners_PartnerId";
                    END IF;
                END $$;

                DROP INDEX IF EXISTS "IX_Products_UnitId";
                DROP INDEX IF EXISTS "IX_ContractPartners_ContractId_PartnerId";
                DROP INDEX IF EXISTS "IX_ContractPartners_PartnerId";
                DROP INDEX IF EXISTS "IX_Currencies_Code";
                DROP INDEX IF EXISTS "IX_Partners_Code";
                DROP INDEX IF EXISTS "IX_Units_Code";

                DROP TABLE IF EXISTS "ContractPartners";
                DROP TABLE IF EXISTS "Currencies";
                DROP TABLE IF EXISTS "Units";
                DROP TABLE IF EXISTS "Partners";

                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public'
                          AND table_name = 'ContractPartners_LegacyBackup')
                    AND NOT EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public'
                          AND table_name = 'ContractPartners')
                    THEN
                        ALTER TABLE "ContractPartners_LegacyBackup" RENAME TO "ContractPartners";
                    END IF;
                END $$;

                ALTER TABLE "SalesTransactions" DROP COLUMN IF EXISTS "AppliedFxRateToUsd";
                ALTER TABLE "SalesTransactions" DROP COLUMN IF EXISTS "Currency";
                ALTER TABLE "SalesTransactions" DROP COLUMN IF EXISTS "TotalInCurrency";
                ALTER TABLE "SalesTransactions" DROP COLUMN IF EXISTS "UnitPriceInCurrency";

                ALTER TABLE "Products" DROP COLUMN IF EXISTS "UnitId";

                ALTER TABLE "ExpenseTransactions" DROP COLUMN IF EXISTS "Amount";
                ALTER TABLE "ExpenseTransactions" DROP COLUMN IF EXISTS "AppliedFxRateToUsd";
                ALTER TABLE "ExpenseTransactions" DROP COLUMN IF EXISTS "Currency";

                ALTER TABLE "Contracts" DROP COLUMN IF EXISTS "AppliedFxRateToUsd";
                ALTER TABLE "Contracts" DROP COLUMN IF EXISTS "OwnershipType";
                ALTER TABLE "Contracts" DROP COLUMN IF EXISTS "UnitPriceInCurrency";
                """);
        }
    }
}
